/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStudioRouteImport } from './routes/_app/studio'
import { Route as AppPlannerRouteImport } from './routes/_app/planner'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppEmailRouteImport } from './routes/_app/email'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCompetitorsRouteImport } from './routes/_app/competitors'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAdsRouteImport } from './routes/_app/ads'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdsRoute = AppAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ads': typeof AppAdsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/competitors': typeof AppCompetitorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/email': typeof AppEmailRoute
  '/library': typeof AppLibraryRoute
  '/planner': typeof AppPlannerRoute
  '/studio': typeof AppStudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ads': typeof AppAdsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/competitors': typeof AppCompetitorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/email': typeof AppEmailRoute
  '/library': typeof AppLibraryRoute
  '/planner': typeof AppPlannerRoute
  '/studio': typeof AppStudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ads': typeof AppAdsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/competitors': typeof AppCompetitorsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/email': typeof AppEmailRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/studio': typeof AppStudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ads'
    | '/analytics'
    | '/competitors'
    | '/dashboard'
    | '/email'
    | '/library'
    | '/planner'
    | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ads'
    | '/analytics'
    | '/competitors'
    | '/dashboard'
    | '/email'
    | '/library'
    | '/planner'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ads'
    | '/_app/analytics'
    | '/_app/competitors'
    | '/_app/dashboard'
    | '/_app/email'
    | '/_app/library'
    | '/_app/planner'
    | '/_app/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email': {
      id: '/_app/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors': {
      id: '/_app/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ads': {
      id: '/_app/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AppAdsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdsRoute: typeof AppAdsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmailRoute: typeof AppEmailRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppStudioRoute: typeof AppStudioRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdsRoute: AppAdsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmailRoute: AppEmailRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppStudioRoute: AppStudioRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
